name: flutter_explained_website
description: Flutter Website of Flutter Explained

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.0.0+1
  url_launcher: ^5.4.2
  json_annotation: ^3.0.1
  storyblok_client:
    path: "../storyblok_client"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true